### ISSUE TITLE
WebOverview failed

### ISSUE THREAD

**Issue by yi-liang** [qca/boardfarm#74]
trying to run the test "WebOverview" and got the error:
AttributeError: 'WebOverview' object has no attribute 'driver'
was "setup()" missed in the "WebOverview" or it's expecting some other tests to run before it?
Thanks

**Comment by mbanders** [comment]
It would help if you copy-pasted the full output, otherwise we are just guessing.

Looking at the code:

``` python
class WebOverview(WebTest)
```

That creates a class `WebOverview` which is a subclass of `WebTest`.  The `WebTest` defines a `setup()` function. So `WebOverview` has that same `setup()` function as well.

**Comment by yi-liang** [comment]
the full output is
==================== Begin WebOverview ====================
Checking overview page

TEST_CASE_RESULT =  FAIL

=========== Test failed! Running recovery ===========
'WebOverview' object has no attribute 'driver'
Traceback (most recent call last):
  File "/home/jenkins/boardfarm/boardfarm/tests/linux_boot.py", line 72, in testWrapper
    self.runTest()
  File "/home/jenkins/boardfarm/boardfarm/tests/webui_tests.py", line 45, in runTest
    action_chains = ActionChains(self.driver)
AttributeError: 'WebOverview' object has no attribute 'driver'
 echo "1 1 1 7" > /proc/sys/kernel/printk

**Comment by mbanders** [comment]
Maybe @miska knows.  Looks like it's not running the `setup()` function for some reason which is neeced so that `self.driver` is created.
